set(MWW_MODELS_DIR ${PROJECT_DIR}/main/audio/wake_words/micro_wake_word/models)

if(CONFIG_MICRO_WAKE_WORD_MODEL_ALEXA)
    set(MWW_MODEL ${MWW_MODELS_DIR}/alexa.tflite)
    set(MWW_MODEL_NAME "alexa")
    set(MWW_MODEL_WAKE_WORD "Alexa")
    set(MWW_MODEL_PROB_CUTOFF 90)
elseif(CONFIG_MICRO_WAKE_WORD_MODEL_HEY_JARVIS)
    set(MWW_MODEL ${MWW_MODELS_DIR}/hey_jarvis.tflite)
    set(MWW_MODEL_NAME "hey_jarvis")
    set(MWW_MODEL_WAKE_WORD "Hey Jarvis")
    set(MWW_MODEL_PROB_CUTOFF 97)
elseif(CONFIG_MICRO_WAKE_WORD_MODEL_HEY_MYCROFT)
    set(MWW_MODEL ${MWW_MODELS_DIR}/hey_mycroft.tflite)
    set(MWW_MODEL_NAME "hey_mycroft")
    set(MWW_MODEL_WAKE_WORD "Hey Mycroft")
    set(MWW_MODEL_PROB_CUTOFF 95)
elseif(CONFIG_MICRO_WAKE_WORD_MODEL_OKAY_NABU)
    set(MWW_MODEL ${MWW_MODELS_DIR}/okay_nabu.tflite)
    set(MWW_MODEL_NAME "okay_nabu")
    set(MWW_MODEL_WAKE_WORD "Okay Nabu")
    set(MWW_MODEL_PROB_CUTOFF 97)
endif()
